namespace EvolveUI.Parsing {

    internal enum SymbolType {

        Invalid = 0,
        BooleanAnd,
        Coalesce,
        ConditionalAccess,
        ConditionalOr,
        FatArrow,
        Equals,
        NotEquals,
        Increment,
        Decrement,
        ThinArrow,
        Assign,
        AddAssign,
        SubtractAssign,
        DivideAssign,
        MultiplyAssign,
        ModAssign,
        AndAssign,
        OrAssign,
        XorAssign,
        LeftShiftAssign,
        RightShiftAssign,
        GreaterThanEqualTo,
        LessThanEqualTo,
        GreaterThan,
        LessThan,
        Not,
        Plus,
        Minus,
        Divide,
        Multiply,
        Modulus,
        BinaryNot,
        BinaryOr,
        BinaryAnd,
        BinaryXor,
        QuestionMark,
        Colon,
        SemiColon,
        DoubleColon,
        Dot,
        At,
        Comma,
        OpenParen,
        CloseParen,
        SquareBraceOpen,
        SquareBraceClose,
        CurlyBraceOpen,
        CurlyBraceClose,
        CoalesceAssign,
        Range,

        HashTag,

        Underscore

    }

}